- hosts: localhost
  var:
    idrac_ip: "10.12.1.14"
    idrac_user: "root"
    idrac_password: "calvin"
    new_idrac_ip: ""
    dns_idrac_name: "bipapp0012"
    raid_slot: "RAID.Slot.1-1"
    enclosure_slot: "Enclosure.Internal.0-1"
  tasks:
  - name: Configure the iDRAC attributes for Syslog Setting
    dellemc.openmanage.idrac_attributes:
      idrac_ip: '{{ idrac_ip }}'
      idrac_user: '{{ idrac_user }}'
      idrac_password: '{{ idrac_password }}'
      validate_certs: false
      idrac_attributes:
        SysLog.1.Server1: "10.2.116.213"
        SysLog.1.SysLogEnable: "Enabled"
  - name: Configure the iDRAC attributes for SMTP Setting
    dellemc.openmanage.idrac_attributes:
      idrac_ip: '{{ idrac_ip }}'
      idrac_user: '{{ idrac_user }}'
      idrac_password: '{{ idrac_password }}'
      validate_certs: false
      idrac_attributes:
        EmailAlert.1.Address: "ITOC-L@telkomsel.co.id"
        EmailAlert.1.Enable: "Enabled"
        EmailAlert.2.Address: "OSPLA-L@telkomsel.co.id"
        EmailAlert.2.Enable: "Enabled"
        EmailAlert.3.Address: "support.telkomsel@ipnetsolusindo.com"
        EmailAlert.3.Enable: "Enabled"
        RemoteHosts.1.SMTPServerIPAddress: "10.38.37.73"
        RemoteHosts.1.SenderEmail: "delltbsesx01-idrac@telkomsel.co.id"
  - name: Convert physical disk to RAID
    dellemc.openmanage.idrac_redfish_storage_controller:
      baseuri: '{{ idrac_ip }}'
      username: '{{ idrac_user }}'
      password: '{{ idrac_password }}'
      validate_certs: false
      command: "ConvertToRAID"
      target: ['Disk.Bay.0:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.1:{{ enclosure_slot }}:{{ raid_slot }}']
  - name: Convert physical disk to non-RAID
    dellemc.openmanage.idrac_redfish_storage_controller:
      baseuri: '{{ idrac_ip }}'
      username: '{{ idrac_user }}'
      password: '{{ idrac_password }}'
      validate_certs: false
      command: "ConvertToNonRAID"
      target: ['Disk.Bay.2:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.3:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.4:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.5:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.6:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.7:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.8:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.9:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.10:{{ enclosure_slot }}:{{ raid_slot }}']
  - name: Create Raid 1 Volume for OS
    dellemc.openmanage.dellemc_idrac_storage_volume:
      idrac_ip: '{{ idrac_ip }}'
      idrac_user: '{{ idrac_user }}'
      idrac_password: '{{ idrac_password }}'
      validate_certs: false
      state: "create"
      controller_id: '{{ raid_slot }}'
      volume_type: "RAID 1"
      disk_cache_policy: "Enabled"
      write_cache_policy: "WriteBack"
      read_cache_policy: "ReadAhead"
      raid_init_operation: "Fast"
      volumes:
        - drives:
          id: ['Disk.Bay.0:{{ enclosure_slot }}:{{ raid_slot }}', 'Disk.Bay.1:{{ enclosure_slot }}:{{ raid_slot }}']
  - name: Configure iDRAC network settings
    dellemc.openmanage.idrac_network:
      idrac_ip: '{{ idrac_ip }}'
      idrac_user: '{{ idrac_user }}'
      idrac_password: '{{ idrac_password }}'
      validate_certs: false
      setup_idrac_nic_vlan: Enabled
      vlan_id: 1303
      vlan_priority: 1
      enable_nic: Enabled
      nic_selection: Dedicated
      ip_address: '{{ new_idrac_ip }}'
      enable_dhcp: Disabled
      enable_ipv4: Enabled
      static_gateway: "10.53.191.254"
      static_net_mask: "255.255.248.0"
      dns_idrac_name: '{{ dns_idrac_name }}'
      static_dns: '{{ static_dns }}'
